### ISSUE TITLE
Most recent Pocket build does not run

### ISSUE THREAD

**Issue by johnlago** [Obalfour/Flooder#3]
The most recent build for Analogue Pocket (with improved input) does not load on the device. Instead, the Pocket displays "error." Love the game, thanks for making this. :)

**Comment by Obalfour** [comment]
I uploaded a fixed version that I tried using emulicious. Since I dont own an analogue pocket, can you please tell me if it works correctly? thank you! (:

**Comment by johnlago** [comment]
Success! Runs perfectly on the Pocket now, and inputs are hugely improved. Thanks!

**Comment by Obalfour** [comment]
Thank you! Have fun (:
